# Generated by Django 4.2 on 2025-11-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('original_file', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('test_size', models.FloatField(default=0.4)),
                ('val_size', models.FloatField(default=0.5)),
                ('random_state', models.IntegerField(default=42)),
                ('stratify_column', models.CharField(blank=True, max_length=100, null=True)),
                ('shuffle', models.BooleanField(default=True)),
                ('original_rows', models.IntegerField()),
                ('original_columns', models.IntegerField()),
                ('train_rows', models.IntegerField()),
                ('val_rows', models.IntegerField()),
                ('test_rows', models.IntegerField()),
            ],
        ),
    ]
